config/routes.rb
Rails.application.routes.draw do
  resources :enquiries
  get 'admin', to: 'pages#admin'

  get 'contact', to: 'pages#contact'

  get 'about', to: 'pages#about'

  resources :photos
  resources :posts
  resources :events
  resources :groups
  resources :group_categories
  resources :profiles
  devise_for :users

  get 'home/index'
  resources :users, only: :destroy
  get 'make_admin/:id', to: 'users#make_admin'

  root 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.has_role? :admin
        can :manage, :all
      else
        can :manage, Profile, user_id: user.id
      end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
  validates :name, :email, :enquiry_type, :message, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :group_events
  has_many :groups, through: :group_events

  validates :street, :suburb, :postcode, :state, presence: true

  acts_as_taggable


  geocoded_by :full_street_address
  after_validation :geocode

  def full_street_address
    [street, suburb, state, postcode, country].compact.join(',')
  end


end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :group_category
  has_many :photos
  has_many :posts
  has_many :group_events
  has_many :events, through: :group_events
  has_many :memberships
  has_many :users, through: :memberships

  extend FriendlyId
  friendly_id :name, use: :slugged

  mount_uploader :logo, ProfilePicUploader
  mount_uploader :banner, ProfilePicUploader


end

app/models/group_category.rb
class GroupCategory < ActiveRecord::Base
  has_many :groups
end

app/models/group_event.rb
class GroupEvent < ActiveRecord::Base
  belongs_to :group
  belongs_to :event
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  validates :first_name, :last_name, :dob, presence: true

  mount_uploader :profile_pic, ProfilePicUploader

  def full_name
    [first_name, last_name].compact.join(' ')
  end

  extend FriendlyId
  friendly_id :full_name, use: :slugged

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_one :profile
  has_many :events
  has_many :posts
  has_many :photos
  has_many :memberships
  has_many :groups, through: :memberships

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :index
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @owner_profile = User.find(@group.owner_id).profile
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:group_category_id, :name, :description, :logo, :banner, :owner_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/groups/_form.html.erb
  <%= simple_form_for(@group) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :group_category %>
    <%= f.input :name %>
    <%= f.input :description %>
    <ul>

    <li>Logo</li>
    <label class="file">
      <%= f.file_field :logo %>
      <span class="file-custom"></span>
    </label>
      <%= f.input_field :logo, as: :file %>


    <li>Banner</li>
    <label class="file">
      <%= f.file_field :banner %>
      <span class="file-custom"></span>
      </label>
      <%= f.input_field :banner, as: :file %>

    </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups</h1>

<table class="table">
  <thead>
    <tr>
      <th>Group category</th>
      <th>Name</th>
      <th>Description</th>
      <th>Logo</th>
      <th>Banner</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.group_category.name %></td>
        <td><%= group.name %></td>
        <td><%= group.description %></td>
        <td><%= cl_image_tag group.logo, width: '50px' %></td>
        <td><%= cl_image_tag group.banner, width: '50px' %></td>
        <td><%= group.owner_id %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<%= content_for :group_name, @group.name %>
<%= content_for :group_banner, @group.banner %>



<p id="notice"><%= notice %></p>

<p>
  <strong>Group category:</strong>
  <%= @group.group_category %>
</p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @group.description %>
</p>

<p>
  <strong>Logo:</strong>
  <%= cl_image_tag @group.logo, width: '50px' %>
</p>

<p>
  <strong>Banner:</strong>
  <%= cl_image_tag @group.banner, width: '50px' %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @owner_profile.full_name %>
</p>

<%= link_to 'Create event', new_event_path,class: 'btn btn-warning' %>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>