config/routes.rb
Rails.application.routes.draw do
  resources :enquiries
  get 'admin', to: 'pages#admin'

  get 'contact', to: 'pages#contact'

  get 'about', to: 'pages#about'

  resources :photos
  resources :posts
  resources :events
  resources :groups
  resources :group_categories
  resources :profiles
  devise_for :users

  get 'home/index'
  resources :users, only: :destroy
  get 'make_admin/:id', to: 'users#make_admin'

  root 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.has_role? :admin
        can :manage, :all
      else
        can :manage, Profile, user_id: user.id
      end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
  validates :name, :email, :enquiry_type, :message, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :group_events
  has_many :groups, through: :group_events

  validates :street, :suburb, :postcode, :state, presence: true

  acts_as_taggable


  geocoded_by :full_street_address
  after_validation :geocode

  def full_street_address
    [street, suburb, state, postcode, country].compact.join(',')
  end


end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :group_category
  has_many :photos
  has_many :posts
  has_many :group_events
  has_many :events, through: :group_events
  has_many :memberships
  has_many :users, through: :memberships

  extend FriendlyId
  friendly_id :name, use: :slugged

  mount_uploader :logo, ProfilePicUploader
  mount_uploader :banner, ProfilePicUploader


end

app/models/group_category.rb
class GroupCategory < ActiveRecord::Base
  has_many :groups
end

app/models/group_event.rb
class GroupEvent < ActiveRecord::Base
  belongs_to :group
  belongs_to :event
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  validates :first_name, :last_name, :dob, presence: true

  mount_uploader :profile_pic, ProfilePicUploader

  def full_name
    [first_name, last_name].compact.join(' ')
  end

  extend FriendlyId
  friendly_id :full_name, use: :slugged

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_one :profile
  has_many :events
  has_many :posts
  has_many :photos
  has_many :memberships
  has_many :groups, through: :memberships

end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <div class="container">

    <a class="navbar-brand" href="/">Community Maker</a>

      

      <ul class="nav navbar-nav pull-md-right">

        <li class="nav-item <%= 'active' if current_page?(root_path) %>">
          <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
        </li>

        <li class = "nav-item <%= 'active' if current_page?(groups_path) %>">
            <a class="nav-link" href="/groups">Groups</a>
        </li>

        <li class = "nav-item <%= 'active' if current_page?(contact_path) %>">
            <a class="nav-link" href="/contact">Contact</a>
        </li>


            <% if user_signed_in? %>
            <% if current_user.profile %>

            <li class="nav-item">
                  <%= link_to 'My Profile', profile_path(current_user.profile), class: 'nav-link' %>
            </li>
            <% else %>

            <li class="nav-item">
            <%= link_to 'Create your profile', new_profile_path, class: 'nav-link' %>
            </li>
            <% end %>

        <% if current_user.has_role? :admin %>
          <li class="nav-item <%= 'active' if current_page?(admin_path) %>"> <%= link_to 'Admin', admin_path, class: 'nav-link' %></li>
        <% end %>

        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
        </li>
        <% end %>


        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>

      </ul>
      <!-- <form class="form-inline pull-xs-right">
      <input class="form-control" type="text" placeholder="Search">
      <button class="btn btn-success-outline" type="submit">Search</button>
    </form> -->

  </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Communitymaker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>

  <% if content_for? :group_name %>
  <section class="group-banner" style="background-image: url(<%= yield(:group_banner) %>); height: 200px;">
    <h1><%= yield(:group_name) %></h1>
  </section>
  <% end %>

  <div class="container">

<%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/admin.html.erb
<h1>Admin</h1>

<h2>Users</h2>
<table class="table">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Admin</th>
    <th></th>

  </tr>

  <% @users.each do |user| %>
    <tr>
       <! -- make this a link to the user's profile page -->
      <td><%= link_to user.profile.full_name, profile_path(user.profile) %></td>
      <td><%= user.email %></td>
      <td><%= user.profile.phone %></td>

      <!-- #bonus for a button that makes the user an admin   -->
      <td><%= link_to 'Make admin', 'make_admin/' + user.id.to_s, class: 'btn btn-info' %></td>
      <!-- delete user -->

        <% if user == current_user %>
        <td><%= link_to 'Edit', edit_user_registration_path(user) %></td>
        <% else %>
      <td><%= link_to 'Delete user', user_path(user), method: :delete, data: {confirm: 'Are you sure?'} %></td>
      <% end %>
      </tr>

      <% end %>
</table>
<hr>
<%= render 'group_categories/index' %>

app/views/pages/contact.html.erb
<h1>Get in touch</h1>
<p>We are friendly</p>

<%= render 'enquiries/form' %>